### ISSUE TITLE
UUID error

### ISSUE THREAD

**Issue by johndavemanuel** [Ibaslogic/simple-todo-app#1]
I think the uuid should be something like

`import { v4 as uuidv4 } from 'uuid';`

then to use it

`id: uuidv4(),`

Great tutorial for react beginners like me by the way

**Comment by Ibaslogic** [comment]
Yeah. This works as well.

**Comment by johndavemanuel** [comment]
This is the error I got I while I am following your tutorial

`'uuid' does not contain a default export (imported as 'uuid')`

**Comment by Ibaslogic** [comment]
Good one from you John. 

As at Version 7, UUID no more export Version 4 as default. That means, we have to specify which type of UUID we need.  

So what you have above should work perfectly.
