### ISSUE TITLE
Minor fix needed at tutorial site

### ISSUE THREAD

**Issue by freakynit** [Ibaslogic/simple-todo-app#2]
Hi, first of all thanks for the awesome react tutorial...Keep up the great work 👍 

Now, the issue:

In 2nd part of tutorial (https://ibaslogic.com/react-form-handling/): 

<img width="552" alt="Screenshot 2021-11-12 at 11 23 48 PM" src="https://user-images.githubusercontent.com/745352/141512560-7dd78aed-0d56-45e8-8c6a-116a1b1a2699.png">

^ I believe it should `not` be referencing `this` because in first part of this tutorial, this component had been changed to functional one.

Thanks...

**Comment by Ibaslogic** [comment]
Thanks Nitin for reading through. Please be aware that the component is class based. In the first part we said this towards the end:

"In this part of the tutorial, we will use the functional component simply for presentation as in the case of the `Header` component. There, we are rendering a simple heading text. *So, let's revert the `TodoItem` component to class component*. Do that quickly" 

Please confirm.

Thank you! Regards.

**Comment by freakynit** [comment]
Oh right... forgot about that line... It's there, can confirm. 

Let me close the issue with appropriate status...

Thanks again for awesome tutorial..
